creation_rules:
  - path_regex: hosts/auresco/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1ngh9jhfe42xag0cp2q9wejackurw7rcp5kj80avdpwyfmeg9gd9swlrhy8

  - path_regex: hosts/cadensia/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1qyjnr69q6jg2nnvq37thqun9esk292t70lrzs5yjjkhj2pp5qsaq4uxgqy

  - path_regex: hosts/ekidno/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1njf4a8s0sckv6n5ua80tkwj90a08p30qtzjaj7m2rt48qe6t7sascptp7d

  - path_regex: hosts/flamii/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1j85fgdkpyh2uh4keysxk08pmmlael75zewpqqr8jt8wajszdmuhqkx7q6g

  - path_regex: hosts/seebu/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1563lf48t3pe4xfzluk7nd3fa0dpak5mpejdzyyt5npc07g233s5qt22th9
