creation_rules:
  - path_regex: terraform/planetscale/credentials.json
    age: age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf

  - path_regex: hosts/syra/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age15szmxhqfa5cyeg558kf2ee8q4h29p2x80la54llr98qctd56purs70yfzd
