creation_rules:
  - path_regex: hosts/auresco/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1ngh9jhfe42xag0cp2q9wejackurw7rcp5kj80avdpwyfmeg9gd9swlrhy8

  - path_regex: hosts/seebu/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1563lf48t3pe4xfzluk7nd3fa0dpak5mpejdzyyt5npc07g233s5qt22th9
