creation_rules:
  - path_regex: hosts/ekidno/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1njf4a8s0sckv6n5ua80tkwj90a08p30qtzjaj7m2rt48qe6t7sascptp7d

  - path_regex: hosts/flamii/secrets.json
    age: >-
      age1pfzj8gxp257vdn4xrjmytcc9yjhxecg8wcly4qj84jd7d2kmldyq9hy9kf,
      age1j85fgdkpyh2uh4keysxk08pmmlael75zewpqqr8jt8wajszdmuhqkx7q6g
