---
manager:
  auto_arpa:
    max_auto_arpa: 1
  validators:
    enabled:
      - strict
      - best-practice

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: .
  local:
    class: octodns_bind.ZoneFileSource
    directory: ./zones
    file_extension: .zone
    hostmaster_email: noc@as212625.net.

zones:
  as212625.net.: { sources: [config], targets: [local] }
  b.2.0.1.4.6.b.c.0.a.2.ip6.arpa.: { sources: [config, auto-arpa], targets: [local] }
  dubreuil.dev.: { sources: [config], targets: [local] }
