---
manager:
  include_meta: false
  max_workers: 2
  validators:
    enabled:
      - strict
      - best-practice

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: .
  local:
    class: octodns_bind.ZoneFileSource
    directory: ./zones
    file_extension: .zone
    hostmaster_email: noc@as212625.net

zones:
  as212625.net.: { sources: [config], targets: [local] }
  dubreuil.dev.: { sources: [config], targets: [local] }
