#! /usr/bin/env nix-shell
#! nix-shell -i python3 -p python311Packages.toml

import re
import subprocess
import toml

def format(value):
  for r in [r'^via *', r'^on *', r'^is *', r'^with *', r'^took *', r'^at *', r'in *$']:
    value = re.sub(r, '', value)
  return value

default_config = toml.loads(subprocess.check_output(['starship', 'print-config', '--default']).decode('utf-8'))

print("# Generated by hack/starship_format.py. DO NOT EDIT.")
print("{")

for key, value in default_config.items():
  if not isinstance(value, dict) or 'format' not in value:
    continue

  formated = format(value['format'])
  if formated != value['format']:
    nix_format = formated.replace("\\", "\\\\").replace("${", "\\${")
    print(f"""
  {key} = {{
    format = "{nix_format}";
  }};
""".strip("\n"))

print("}")
