# Generated by ./update.sh. DO NOT EDIT.
{
  boundary = {
    version = "0.13.1";
    sha256 = {
      x86_64-linux = "7e549922c0cb31e46fbbbb52eaa6cfccbf40046b8a50844adf644c9ef335cb97";
      aarch64-linux = "5d7cb7041ec6d561b256c9439e83c573da7a5f8a5146fa661c77a77457386c7c";
    };
  };
  consul = {
    version = "1.16.1";
    sha256 = {
      x86_64-linux = "1d48942fa9f1d0df3f56a1622c7a46e9b85924ed9976338912101bb5519aadf1";
      aarch64-linux = "b949438fddc180825fe8917dd58ed80282b2ed4eea7c9f421ccec0c23cf77507";
    };
  };
  nomad = {
    version = "1.6.1";
    sha256 = {
      x86_64-linux = "e4c01c51c393b266aee4ff184dd97704ae3d838c233a6189425a9f1c31a55f4f";
      aarch64-linux = "67b2b2b62cee102f7436391588f67440d44737b75c3d29dfebec94948928374d";
    };
  };
  packer = {
    version = "1.9.4";
    sha256 = {
      x86_64-linux = "6cd5269c4245aa8c99e551d1b862460d63fe711c58bec618fade25f8492e80d9";
      aarch64-linux = "f00a4fc221b20a166cfac8a63513054775988a068667517bb3edcfab8b1700ba";
    };
  };
  terraform = {
    version = "1.5.7";
    sha256 = {
      x86_64-linux = "c0ed7bc32ee52ae255af9982c8c88a7a4c610485cf1d55feeb037eab75fa082c";
      aarch64-linux = "f4b4ad7c6b6088960a667e34495cae490fb072947a9ff266bf5929f5333565e4";
    };
  };
  vault = {
    version = "1.14.2";
    sha256 = {
      x86_64-linux = "134a4b8d9473722b2d37d4677e8e5c7e18f5010f8866c4bbb84e2cef3daea532";
      aarch64-linux = "ce4c5eb14c1362a2513d60592b91b3b3a0076bd564df90d1ba2c675b3a719717";
    };
  };
  waypoint = {
    version = "0.11.4";
    sha256 = {
      x86_64-linux = "96d314f1bc182a30ca9e93910981fbd4ecf7290763c55d2d4e8ddce2b23abdca";
      aarch64-linux = "bbf331be8785a99a0bfcb4707a013355ba58516d0e9b1b78fd8808e4d2213e66";
    };
  };
}
