# Generated by ./update.sh. DO NOT EDIT.
{
  boundary = {
    version = "0.16.2";
    sha256 = {
      x86_64-linux = "42618e2f1f0e413ad8a9abc5d731dd425b135446e8f007e38057132b51b066d3";
      aarch64-linux = "541a530f3da2e79aa054d0812790c2c60a75225ff5e89c316b4e3a26a0833685";
    };
  };
  consul = {
    version = "1.19.0";
    sha256 = {
      x86_64-linux = "e337fba12295fc7bab177a84a7616eb8bcc827f032a2982c8c0e417fbe86541f";
      aarch64-linux = "6956d1bf8070a37fdbdbdfc018fb7aad7ab24ea9867d0f05dad35c7e26a43f33";
    };
  };
  nomad = {
    version = "1.8.1";
    sha256 = {
      x86_64-linux = "29f91e539562bd377b9ecb82dd928526e24d0ef2b11537960fbbbb200713dc36";
      aarch64-linux = "b3cd3cb6dcfb4b022272d8c0a594f0d0aacb0ede9855ef2a5a707c4fcfe1715c";
    };
  };
  packer = {
    version = "1.11.1";
    sha256 = {
      x86_64-linux = "07a9d92fe98d7bb4be09392c06ef6c4f9ffbc905fe6c29fff0622432367f01cc";
      aarch64-linux = "2666f40bde53f4684ba5a3d52a38c02d6ba45fd114c38ea6a0925bedd2e16ad0";
    };
  };
  terraform = {
    version = "1.9.1";
    sha256 = {
      x86_64-linux = "c3e1dade1c81fdc5e293529e480709f047c0113ea9feb8d9f35002df09ec6a34";
      aarch64-linux = "f1426fccbf2500202b37993ef6b92e1fc60d114dd32c79bfadbc843929b2c7e2";
    };
  };
  vault = {
    version = "1.17.1";
    sha256 = {
      x86_64-linux = "f2266dcecabff8809a54f7cf3688c1946408e8f863bcf379ef9146ab3a1c3f4a";
      aarch64-linux = "6f6449cb8d353af99c8506f92b9b53111def3daba32c72f2483a8ae98faff2f2";
    };
  };
}
