# Generated by ./update.sh. DO NOT EDIT.
{
  boundary = {
    version = "0.14.3";
    sha256 = {
      x86_64-linux = "284ffea85f2853b87b783a2d1e6cd4ceb0b0c3ad8d15233cd7d634ce53363327";
      aarch64-linux = "e18b335cdddcffefdc60e496dd39770f5936f7ac014d23cd019a2e7cb7e99dc5";
    };
  };
  consul = {
    version = "1.17.1";
    sha256 = {
      x86_64-linux = "388889321d6aaf389ee87acc247ea9885e684a1581c8ebfbeab7348abd7c0214";
      aarch64-linux = "f36e1add92439cac710f2546beac97f9a6478fab9ff2342f3ce13f72ef2650de";
    };
  };
  nomad = {
    version = "1.7.3";
    sha256 = {
      x86_64-linux = "ee0d93fe1b2d5aead6bc5c0508c8ac99822e11157c0e1172f5da0d7d139c26c8";
      aarch64-linux = "5d986363290109cbcdce889b1e7b6ec01b86a3759ec56930c78ae0bebfb65f15";
    };
  };
  packer = {
    version = "1.10.0";
    sha256 = {
      x86_64-linux = "a8442e7041db0a7db48f468e353ee07fa6a7b35276ec62f60813c518ca3296c1";
      aarch64-linux = "37149ec9ca322aa50f249a645e43e67498b67e785b356c59f9b0f0e6519da78e";
    };
  };
  terraform = {
    version = "1.7.0";
    sha256 = {
      x86_64-linux = "2bac080244845ebd434baf5e8557bd06d53b3c8bc01b7e496b390a56cb40ac5c";
      aarch64-linux = "33094b8c677460e7c6496a89770ae702bb8d9c6613d4a8485897da006d1919b5";
    };
  };
  vault = {
    version = "1.15.4";
    sha256 = {
      x86_64-linux = "f42f550713e87cceef2f29a4e2b754491697475e3d26c0c5616314e40edd8e1b";
      aarch64-linux = "79aee168078eb8c0dbb31c283e1136a7575f59fe36fccbb1f1ef6a16e0b67fdb";
    };
  };
  waypoint = {
    version = "0.11.4";
    sha256 = {
      x86_64-linux = "96d314f1bc182a30ca9e93910981fbd4ecf7290763c55d2d4e8ddce2b23abdca";
      aarch64-linux = "bbf331be8785a99a0bfcb4707a013355ba58516d0e9b1b78fd8808e4d2213e66";
    };
  };
}
