#!/bin/sh

set -euo pipefail

get_release() {
  version="$(curl -sS "https://api.releases.hashicorp.com/v1/releases/$1/latest?license_class=oss" | jq -r .version)"
  sha256="$(curl -sS "https://releases.hashicorp.com/${1}/${version}/${1}_${version}_SHA256SUMS")"

  cat <<EOL
  $1 = {
    version = "${version}";
    sha256 = {
      x86_64-linux = "$(echo "$sha256" | grep linux_amd64 | cut -d\  -f1)";
      aarch64-linux = "$(echo "$sha256" | grep linux_arm64 | cut -d\  -f1)";
    };
  };
EOL
}

echo "# Generated by $0. DO NOT EDIT."
echo "{"

for name in consul nomad packer terraform vault waypoint; do
  get_release $name
done

echo "}"
