router id 51.254.131.24;

protocol static {
    ipv6;
    route 2a0c:b641:2b0:1::/64 blackhole;
}

protocol kernel {
    kernel table 212625;
    ipv6 {
        export filter {
            if source = RTS_DEVICE then reject;
            if(net ~ [ ::/0 ]) then reject;
            accept;
        };
    };
}

template bgp AS212625 {
    local as 65000;
    ipv6 {
        import filter upstream_import_v6;
        export filter {
            if(net ~ [ 2a0c:b641:2b0::/44{56,64} ]) then accept;
            reject;
        };
    };
}

protocol bgp U_EKIDNO from AS212625 {
    neighbor EKIDNO_IP as 212625;
    interface "wg-ekidno";
}

protocol bgp U_FLAMII from AS212625 {
    neighbor FLAMII_IP as 212625;
    interface "wg-flamii";
}
