# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a0d3b80e-031d-477e-baf7-d45496e4929e";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=root" ];
    };

  boot.initrd.luks.devices."main".device = "/dev/disk/by-uuid/65f255b5-a63f-4e47-85be-aee78d700afd";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a0d3b80e-031d-477e-baf7-d45496e4929e";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=nix" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/a0d3b80e-031d-477e-baf7-d45496e4929e";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=docker" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/782E-35B7";
      fsType = "vfat";
    };

  fileSystems."/var/lib/nixos-containers" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "noatime" "mode=755" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
